name: Build Kernel
on:
  push:
    branches:
    - test

jobs:
  KSUForChef:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y lld binutils clang llvm zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full ccache
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/rushiranpise/android_kernel_motorola_msm8998.git --depth=1 -b test
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1 --single-branch --no-tags -b master ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/rushiranpise/AnyKernel3.git
      - name: Add KernelSU to Kernel Source Tree
        run: |
           cd android_kernel_motorola_msm8998
#           get fetch https://github.com/rushiranpise/android_kernel_motorola_msm8998 ksu && git cherry-pick 92a6276987bcdf05a2ef057900222c2f25c8bbef 
#           curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/clang-r487747/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_motorola_msm8998
          make O=out LLVM=1 LLVM_IAS=1 CC="ccache clang" lineageos_chef_defconfig
          make O=out LLVM=1 LLVM_IAS=1 CC="ccache clang" -j$(grep -c ^processor /proc/cpuinfo)
          popd
          
      - name: Creating Config Info
        run: |
          echo "Device: Motorola One Power
          Source Code Tree: LineageOS branch:lineage-20.0
          Code: chef
          Contain KernelSU: YES(Manully_Intergrate)
          Build Code: $(date +%Y%m%d)_${{ github.run_number }}
          Only For LineageOS
          " >> INFO.txt
          
      - name: Packaging the Kernel
        run: |
          cp -v android_kernel_motorola_msm8998/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../android_kernel_motorola_msm8998.zip *
          popd
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: android_kernel_motorola_msm8998.zip
          name: " android_kernel_motorola_msm8998"
          tag: " ${{ github.run_number }}_android_kernel_motorola_msm8998"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
